### PR TITLE
fix: Send root span data as Event.Extra

### LINKED ISSUE #311: [0.9.0] Setting data & status on root span has no impact
## Summary
Hi, i've been using the new tracing system from the golang library, good job!
I've been unable to set data & level on a trace, though

## Steps To Reproduce

```go
span := sentry.StartSpan(ctx, name)
span.Status = sentry.SpanStatusInternalError

span.Data = map[string]interface{}{
"body":        c.Request().Body,
"path":        c.Path(),
"queryParams": c.QueryParams(),
"paramValues": c.ParamValues(),
}
span.Finish()
```

## Expected Behavior
See the data in the UI

### SDK
 - `sentry-go` version: 0.9.0
 - Go version: 1.15.0
 - Using Go Modules? yes

### Sentry
 - Using hosted Sentry in sentry.io? no
 - Using your own Sentry installation? Version: 20.12.1

### PR DESCRIPTION
**Pull request by rhcarvalho**
Pending spec clarification since implementation in Relay and different
SDKs diverged.

For now sending data in Event.Extra gets the information into the
Transaction view in Sentry.

Fixes #311.

### CODE REVIEW

**Review by kamilogorek — APPROVED** [review]

File: tracing_test.go [hunk 1]
```diff
@@ -137,7 +141,7 @@ func TestStartSpan(t *testing.T) {
 		Tags: nil,
 		// TODO(tracing): Set Transaction.Data here or in
 		// Contexts.Trace, or somewhere else. Currently ignored.
-		Extra:     nil,
+		Extra:     span.Data,
```
Comment (kamilogorek) [inline tracing_test.go:144]: Does the comment above still stands if we set it now?

Comment (rhcarvalho) [reply tracing_test.go:145]: Thanks for noticing, it was stale. I moved the comment over from `tracing.go` here.
