### PR TITLE
fix(stacktrace): Correctly report package names and ignore subpackages

### LINKED ISSUE #126: stacktrace: deconstructFunctionName returns bad output for methods
`deconstructFunctionName` puts `.(Hub)` (receiver) in `frame.Module`, but it should be a part of the function (method) name.

_Originally posted by @kamilogorek in https://github.com/getsentry/sentry-go/pull/125/files#r359295441_

### PR DESCRIPTION
**Pull request by rhcarvalho**
Makes function receivers part of the function name and not part of the package name.

Add tests and fix `filteredFrames` to ensure it ignores all packages related to the SDK.

Fixes #126.

### CODE REVIEW

File: stacktrace.go [hunk 1]
```diff
@@ -206,8 +215,7 @@ func filterFrames(frames []Frame) []Frame {
 			continue
 		}
 		// sentry internal frames
-		if frame.Module == "github.com/getsentry/sentry-go" ||
-			strings.HasPrefix(frame.Module, "github.com/getsentry/sentry-go.") {
+		if frame.Module == "github.com/getsentry/sentry-go" {
```
Comment (untitaker) [inline stacktrace.go]: Will this be `github.com/getsentry/sentry-go/fasthttp` for integrations? I feel like it should be if we want to be close to Python.

File: stacktrace.go [hunk 2]
```diff
@@ -226,21 +234,42 @@ func isInAppFrame(frame Frame) bool {
...
 	callerFrame, _ := callersFrames.Next()
-	_, function := deconstructFunctionName(callerFrame.Function)
-	return function
+	return baseName(callerFrame.Function)
+}
+
+// packageName returns the package part of the symbol name, or the empty string
+// if there is none.
+// It replicates https://golang.org/pkg/debug/gosym/#Sym.PackageName, avoiding a
+// dependency on debug/gosym.
```
Comment (rhcarvalho) [inline stacktrace.go]: This is intentional, because:

1. https://go-proverbs.github.io, ["A little copying is better than a little dependency."](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=9m28s)
2. Avoids increasing the size of binaries that include the SDK (see #75)

File: stacktrace.go (hunk 1 above)
Comment (rhcarvalho) [inline stacktrace.go]: See https://github.com/getsentry/sentry-go/pull/125#discussion_r359278184

Comment (rhcarvalho) [reply stacktrace.go]: Yes it will be, and we should filter it out -- what we don't :( Yet.

I realize #125 was incomplete, we need to filter out frames of all packages belonging to the SDK (keeping the behavior of the latest released version).

Thanks for asking! I'll fix it.

Comment (rhcarvalho) [reply stacktrace.go]: Fixed in the latest patch.
